### ISSUE TITLE
How did it go?

### ISSUE THREAD

**Issue by gustafnk** [christopherdumas/Rember#1]
I read your notes, sound interesting :) Did you solve your problems?

**Comment by alexispurslane** [comment]
Sorry for not responding. This was a side-project and high school has kept me busy until now. Unfortunately, although I am finished the Mini-Framework (I'm pretty satisfied with its feature-set and ease of use), I can't seem to get Broccoli to cooperate. Do you had any pointers? I can't even get Broccoli to simply compile my TypeScript files!

**Comment by gustafnk** [comment]
No problem, sometimes we're all busy :)

Sorry, I don't have any pointers at all. Maybe write a question in the Ember forum?

**Comment by alexispurslane** [comment]
I'm currently in the middle of huge projects right now (github.com/christopherdumas/Skyspace, github.com/shymega/guile-rs) but would like to eventually revive this, so don't count it dead yet! With me, nothing's ever _really_ dead. 😄

**Comment by gustafnk** [comment]
:)
